/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.fest.swing.fixture.FrameFixture;
import org.fest.swing.fixture.JComboBoxFixture;
import org.fest.swing.fixture.JPanelFixture;
import org.junit.*;
import java.awt.*;
import javax.swing.*;

import java.util.ArrayList;
import java.util.HashMap;

import static org.junit.Assert.*;

public class GUITest {
    public FrameFixture frame;
    public App app;
    public JPanelFixture contentFixture;
    public ReadJSON jsonReader;
    /*
    @Before
    public void setUp(){



        App app = new App();
        app.initializeUser("src/main/users.txt");
        app.setTitle("Group 2 vending machine");
        app.setSize(800, 800);
        app.setResizable(false);
        app.setLayout(null);
        Font f = new Font("Times New Roman", Font.PLAIN, 18);
        app.JComboBoxConstruction();

        frame = new FrameFixture(app);



    }

    @After
    public void tearDown(){
        frame.cleanUp();
    }

    @Test
    public void TestCreateButton(){
        contentFixture = frame.panel("customer");
        contentFixture.button("Create new account").click();
        contentFixture = frame.panel("create");
        contentFixture.button("BackCreate").click();
    }

    @Test
    public void TestLoginButton(){
        contentFixture = frame.panel("customer");
        contentFixture.button("Login account").click();
        contentFixture = frame.panel("login");
        contentFixture.button("BackLogin").click();
    }

    @Test
    public void TestCreateNewAccount(){
        contentFixture = frame.panel("customer");
        contentFixture.button("Create new account").click();
        contentFixture = frame.panel("create");
        contentFixture.button("Create new account").click();
        contentFixture.label("createStatus").requireText("User name and password cannot be empty!");
        contentFixture.textBox("Name: ").enterText("1");
        contentFixture.textBox("Password: ").enterText("1");
        contentFixture.button("Create new account").click();
        contentFixture.label("createStatus").requireText("User already existed. Please try again.");
    }

    @Test
    public void TestCustomerBuy(){
        contentFixture = frame.panel("customer");
        contentFixture.button("Login account").click();
        contentFixture = frame.panel("login");
        contentFixture.textBox("Name: ").enterText("1");
        contentFixture.textBox("Password: ").enterText("1");
        contentFixture.button("Login account").click();
        contentFixture = frame.panel("customer");
        contentFixture.comboBox("chipbox").selectItem(2);
        contentFixture.textBox("chip").enterText("1");
        contentFixture.button("selectChip").click();
    }
    */
}
