/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.json.simple.*;
import org.junit.*;
import static org.junit.Assert.*;

public class ReadJSONTest {

    public ReadJSON jsonReader;


    @Test
    public void TestInvaildFilePath() throws Exception{
        jsonReader = new ReadJSON("src/test/invalid_cards.json");
    }

    @Test
    public void TestSuccessOpen() {
        jsonReader = new ReadJSON("src/test/credit_cards.json");
        assertNotNull(jsonReader.getAccounts());
    }
}
